---
title: "Are we living in a depressive society?"
subtitle: "Trends in symptoms of anxiety or depressive disorder in the US population from May 2020 to March 2024"
author: Chay Park
thanks: "Code and data are available at: https://github.com/Chay-HyunminPark/Anxiety_depressive_disorder."
date: today
date-format: long
abstract: "This study explores how socio-cultural factors like age, sex, race/ethnicity, and education level influenced anxiety and depressive disorders in the U.S. during and after the COVID-19 pandemic, analyzing data from 2020 to 2024. Using advanced statistical methods in R, it uncovered significant variations in mental health impacts across different demographic groups. The research reveals a complex relationship between socio-cultural factors and mental health, highlighting the increased vulnerability of certain populations during global crises. These insights are crucial for developing targeted public health strategies to mitigate mental health issues during and after pandemics, enhancing our understanding of how socio-cultural dynamics shape mental wellness in times of crisis."
format: pdf
number-sections: true
bibliography: references.bib
---


# Introduction

Depression and anxiety are not only prevalent but escalating issues in the modern world, affecting individuals across the globe regardless of demographic factors (World Health Organization, 2021). These mental health challenges have been further exacerbated by the COVID-19 pandemic, which led to widespread social and economic upheaval (Brooks et al., 2020). While various studies have explored the impact of the pandemic on mental health, there remains a significant gap in understanding the nuanced interactions between socio-cultural factors and the prevalence of anxiety and depressive disorders during this period (Pfefferbaum & North, 2020).

This paper addresses this gap by analyzing data from the U.S. Census Bureau's Household Pulse Survey, initiated in response to the pandemic to assess its effects on American households, including mental wellness (U.S. Census Bureau, 2020). Our analysis focuses on the correlation between the prevalence of anxiety or depressive disorders and socio-cultural factors such as age, sex, race/ethnicity, and education level during the pandemic and post pandemic years of 2020 to 2024. Specifically, the estimand of this study is the difference in the rates of symptoms of anxiety or depressive disorders across individuals, correlated with socio-cultural factors including age, sex, race/ethnicity, and education level.

Employing a quantitative methodology, this paper utilizes R (R Core Team 2020) for analysis. We utilized packages like ggplot2 (Wickham et al., 2016) and gridExtra (Murrell, 2021) for data analysis and visualization. Our findings reveal significant trends and disparities in the rates of anxiety and depressive disorders across different socio-cultural groups, highlighting the intricate relationship between these factors and mental health outcomes during the pandemic.

The importance of this research lies in its potential to inform public health policies and interventions, aiming to mitigate the adverse effects of such global crises on mental health (Xiong et al., 2020). By understanding the specific socio-cultural factors that contribute to increased vulnerability to anxiety and depressive disorders, targeted strategies can be developed to support affected populations more effectively.

The paper is structured to first present the trend analysis of anxiety and depressive disorder rates in the U.S. from 2020 to 2024, followed by an examination of how these rates vary across different demographic groups. Subsequent sections delve into the statistical methods and results for each research question, culminating in a discussion that synthesizes the findings and explores their broader implications for mental health research and policy. The conclusion summarizes the key insights, acknowledges the limitations of the study, and suggests avenues for future research.

The study focuses on answering the following research questions:

* What is the trend in US anxiety and depressive disorder rates from 2020 to 2024?

* How do anxiety and depressive rates vary across different age groups?

* How do anxiety and depressive rates differ based on race and ethnicity?

* How do anxiety and depressive rates differ based on sex?

* How do anxiety and depressive rates differ based on education level?

# Data {#sec-data}

## Methodology

## Features

# Results

## Trend in US Anxiety and Depressive Disorder Rates

```{r}
#| echo: false
#| eval: true
#| warning: false
#| message: false
#| label: fig-andtrend-graph
#| fig-cap: "Trend in US Anxiety and Depressive Disorder Rates"

install.packages("here")

# Load necessary libraries
library(tidyverse)
library(lubridate)
library(here)

# Load the dataset
data <- read.csv(file = here::here("inputs/data/Anxiety_or_Depression.csv"))

# Filter the dataset for 'National Estimate' under 'Group' column and select indicators of interest

filtered_data <- data %>%
  filter(Group == "National Estimate" & Indicator %in% c("Symptoms of Anxiety Disorder", 
                                                         "Symptoms of Depressive Disorder", 
                                                         "Symptoms of Anxiety Disorder or Depressive Disorder"))

# Create a YearMonth column from 'Time Period Label'

filtered_data <- filtered_data %>%
  mutate(YearMonth = as.Date(paste0(sub("^(\\d{4}).+", "\\1", `Time Period Label`), 
                                    ".", 
                                    sub(".+(\\d{2})$", "\\1", `Time Period Label`), 
                                    "01"), format="%Y.%m.%d"))

# Aggregate the data by YearMonth and Indicator
aggregated_data <- filtered_data %>%
  group_by(YearMonth, Indicator) %>%
  summarise(AverageValue = mean(Value, na.rm = TRUE))

# Plot the data
ggplot(aggregated_data, aes(x = YearMonth, y = AverageValue, color = Indicator)) +
  geom_line() +
  scale_x_date(date_breaks = "6 months", date_labels = "%Y.%m") +
  labs(
    title = "National Estimates of Mental Health Symptoms",
    subtitle = "Trends of Symptoms of Anxiety and Depressive Disorders",
    x = "Year",
    y = "Rate (%)",
    color = "Indicator"
  ) +
  theme_minimal()

```


## Trends in Anxiety and Depressive Disorder Rates by Population Subgroup


# Model



## Model set-up


### Model justification


# Discussion

## Findings

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Ethical Implication

## Limitation

The survey was designed to meet the goal of accurate and timely weekly estimates. Hence, it was conducted by an internet questionnaire, with invitations to participate sent by email and text message. 

## Future Research


\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check


## Diagnostics



\newpage


# References

---
nocite: '@*'
---

